#!/usr/bin/env python3
"""sitegen - Minimal static site generator from Markdown. Zero deps."""
import sys, os, re, json, time

def md_to_html(md):
    """Minimal Markdown → HTML converter."""
    html = md
    # Headers
    html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.M)
    html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.M)
    html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.M)
    # Bold/italic
    html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
    html = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html)
    # Code
    html = re.sub(r'`([^`]+)`', r'<code>\1</code>', html)
    # Links
    html = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', html)
    # Images
    html = re.sub(r'!\[([^\]]*)\]\(([^)]+)\)', r'<img src="\2" alt="\1">', html)
    # Lists
    html = re.sub(r'^- (.+)$', r'<li>\1</li>', html, flags=re.M)
    html = re.sub(r'(<li>.*</li>\n?)+', lambda m: '<ul>\n' + m.group(0) + '</ul>\n', html)
    # Paragraphs
    blocks = html.split('\n\n')
    result = []
    for block in blocks:
        block = block.strip()
        if not block: continue
        if block.startswith('<'): result.append(block)
        else: result.append(f'<p>{block}</p>')
    return '\n'.join(result)

def parse_frontmatter(text):
    """Extract YAML-like frontmatter."""
    meta = {}
    content = text
    if text.startswith('---'):
        parts = text.split('---', 2)
        if len(parts) >= 3:
            for line in parts[1].strip().splitlines():
                if ':' in line:
                    k, v = line.split(':', 1)
                    meta[k.strip()] = v.strip().strip('"').strip("'")
            content = parts[2]
    return meta, content

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: system-ui, -apple-system, sans-serif; max-width: 720px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #333; }}
        h1 {{ margin: 1rem 0; }} h2 {{ margin: 0.8rem 0; }} h3 {{ margin: 0.6rem 0; }}
        p {{ margin: 0.5rem 0; }} code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
        a {{ color: #0066cc; }} ul {{ margin: 0.5rem 0 0.5rem 1.5rem; }}
        nav {{ margin-bottom: 2rem; padding-bottom: 1rem; border-bottom: 1px solid #eee; }}
        nav a {{ margin-right: 1rem; text-decoration: none; }}
        .date {{ color: #888; font-size: 0.9rem; }}
        footer {{ margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #eee; color: #888; font-size: 0.8rem; }}
    </style>
</head>
<body>
    <nav>{nav}</nav>
    {content}
    <footer>Generated by sitegen</footer>
</body>
</html>"""

def build_site(src="content", out="public", site_name="My Site"):
    os.makedirs(out, exist_ok=True)
    pages = []
    
    for f in sorted(os.listdir(src)):
        if not f.endswith('.md'): continue
        with open(os.path.join(src, f)) as fh:
            text = fh.read()
        
        meta, content = parse_frontmatter(text)
        html_content = md_to_html(content.strip())
        title = meta.get('title', f.replace('.md','').replace('-',' ').title())
        date = meta.get('date', '')
        slug = f.replace('.md', '.html')
        
        pages.append({"title": title, "slug": slug, "date": date, "meta": meta})
        
        date_html = f'<p class="date">{date}</p>' if date else ''
        full_html = TEMPLATE.format(
            title=f"{title} - {site_name}",
            nav=f'<a href="index.html">{site_name}</a>',
            content=f'<h1>{title}</h1>\n{date_html}\n{html_content}'
        )
        
        with open(os.path.join(out, slug), 'w') as fh:
            fh.write(full_html)
    
    # Index page
    index_content = f'<h1>{site_name}</h1>\n<ul>\n'
    for p in sorted(pages, key=lambda x: x.get('date',''), reverse=True):
        date_str = f' <span class="date">({p["date"]})</span>' if p["date"] else ''
        index_content += f'<li><a href="{p["slug"]}">{p["title"]}</a>{date_str}</li>\n'
    index_content += '</ul>'
    
    index_html = TEMPLATE.format(title=site_name, nav=f'<strong>{site_name}</strong>',
                                  content=index_content)
    with open(os.path.join(out, 'index.html'), 'w') as f:
        f.write(index_html)
    
    return pages

def cmd_build(args):
    src = "content"; out = "public"; name = "My Site"
    for i, a in enumerate(args):
        if a == "--src" and i+1 < len(args): src = args[i+1]
        if a == "--out" and i+1 < len(args): out = args[i+1]
        if a == "--name" and i+1 < len(args): name = args[i+1]
    
    if not os.path.isdir(src):
        print(f"❌ {src}/ not found. Run 'sitegen init' first."); sys.exit(1)
    
    pages = build_site(src, out, name)
    print(f"✅ Built {len(pages)} pages → {out}/")

def cmd_init(args):
    os.makedirs("content", exist_ok=True)
    with open("content/hello.md", "w") as f:
        f.write("---\ntitle: Hello World\ndate: 2026-01-01\n---\n\n# Welcome\n\nThis is your first post.\n\n- Easy to write\n- **Markdown** powered\n- Zero dependencies\n")
    with open("content/about.md", "w") as f:
        f.write("---\ntitle: About\n---\n\n# About\n\nThis site was generated with sitegen.\n")
    print("✅ Created content/ with sample pages")

CMDS = {"build":cmd_build,"b":cmd_build,"init":cmd_init}

if __name__ == "__main__":
    args = sys.argv[1:]
    if not args or args[0] in ("-h","--help"):
        print("sitegen - Static site generator from Markdown")
        print("Commands: init, build [--src content] [--out public] [--name 'Site']")
        sys.exit(0)
    cmd = args[0]
    if cmd not in CMDS: print(f"Unknown: {cmd}"); sys.exit(1)
    CMDS[cmd](args[1:])
